const QUESTION_BANK = {
    "Tarih_P1": [
        { "q": "Türkiye Cumhuriyeti hangi yıl kurulmuştur?", "o": ["1920", "1923", "1924", "1921"], "c": 1 },
        { "q": "İstanbul'un fethi hangi tarihtir?", "o": ["1071", "1453", "1299", "1517"], "c": 1 },
        { "q": "Osmanlı'nın ilk padişahı?", "o": ["Osman Bey", "Orhan Bey", "I. Murat", "Fatih"], "c": 0 },
        { "q": "Kurtuluş Savaşı bitiş yılı?", "o": ["1919", "1920", "1922", "1923"], "c": 2 },
        { "q": "Malazgirt Meydan Muharebesi?", "o": ["1040", "1071", "1243", "1453"], "c": 1 },
        { "q": "Ankara ne zaman başkent oldu?", "o": ["1920", "1921", "1923", "1924"], "c": 2 },
        { "q": "Lozan Antlaşması yılı?", "o": ["1921", "1922", "1923", "1924"], "c": 2 },
        { "q": "İlk TBMM ne zaman açıldı?", "o": ["1919", "1920", "1921", "1922"], "c": 1 },
        { "q": "Atatürk'ün doğum yılı?", "o": ["1880", "1881", "1882", "1883"], "c": 1 },
        { "q": "Atatürk nerede doğdu?", "o": ["İstanbul", "Selanik", "Ankara", "Manastır"], "c": 1 },
        { "q": "Fransız İhtilali yılı?", "o": ["1789", "1799", "1815", "1848"], "c": 0 },
        { "q": "Rönesans nerede başladı?", "o": ["Fransa", "İtalya", "Almanya", "İngiltere"], "c": 1 },
        { "q": "Amerika'yı kim keşfetti?", "o": ["Vasco da Gama", "Kristof Kolomb", "Macellan", "Vespucci"], "c": 1 },
        { "q": "Pusulayı kim icat etti?", "o": ["Çinliler", "Araplar", "Romalılar", "Mısırlılar"], "c": 0 },
        { "q": "Matbaayı kim icat etti?", "o": ["Leonardo", "Gutenberg", "Newton", "Tesla"], "c": 1 },
        { "q": "Sanayi Devrimi nerede başladı?", "o": ["Almanya", "Fransa", "İngiltere", "ABD"], "c": 2 },
        { "q": "II. Dünya Savaşı bitişi?", "o": ["1944", "1945", "1946", "1948"], "c": 1 },
        { "q": "Sümerler nereye yerleşmişti?", "o": ["Mısır", "Mezopotamya", "Anadolu", "Hindistan"], "c": 1 },
        { "q": "Yazıyı kim buldu?", "o": ["Hititler", "Sümerler", "Mısırlılar", "Lidyalılar"], "c": 1 },
        { "q": "Parayı kim icat etti?", "o": ["Sümerler", "Lidyalılar", "Asurlar", "Persler"], "c": 1 },
        { "q": "Magna Carta hangi ülkededir?", "o": ["Fransa", "İngiltere", "Almanya", "İtalya"], "c": 1 },
        { "q": "Büyük İskender nerelidir?", "o": ["Makedonya", "Yunanistan", "Pers", "Mısır"], "c": 0 },
        { "q": "Roma'yı kim kurdu (efsane)?", "o": ["Sezar", "Augustus", "Romulus", "Neron"], "c": 2 },
        { "q": "Bizans'ın diğer adı?", "o": ["Batı Roma", "Doğu Roma", "Kutsal Roma", "Latin İmparatorluğu"], "c": 1 },
        { "q": "Haçlı Seferleri kime karşıydı?", "o": ["Vikingler", "İslam Dünyası", "Romalılar", "Moğollar"], "c": 1 },
        { "q": "Moğol İmparatorluğu kurucusu?", "o": ["Timur", "Cengiz Han", "Hülagü", "Kubilay"], "c": 1 },
        { "q": "Piri Reis'in ünlü eseri?", "o": ["Kitab-ı Bahriye", "Seyahatname", "Nutuk", "Mektubat"], "c": 0 },
        { "q": "Mimar Sinan'ın kalfalık eseri?", "o": ["Selimiye", "Süleymaniye", "Şehzade", "Sultanahmet"], "c": 1 },
        { "q": "Fatih Sultan Mehmet kaç dil biliyordu?", "o": ["2", "4", "6", "8"], "c": 2 },
        { "q": "Kanuni Sultan Süleyman kaç yıl tahtta kaldı?", "o": ["36", "40", "46", "52"], "c": 2 },
        { "q": "Preveze Deniz Zaferi kiminle yapıldı?", "o": ["Haçlı Donanması", "Venedik", "Ceneviz", "İspanya"], "c": 0 },
        { "q": "Trablusgarp Savaşı kiminle yapıldı?", "o": ["Fransa", "İngiltere", "İtalya", "Rusya"], "c": 2 },
        { "q": "Uşi Antlaşması ile neresi kaybedildi?", "o": ["Mısır", "Libya (Trablusgarp)", "Cezayir", "Tunus"], "c": 1 },
        { "q": "Balkan Savaşları başlangıç yılı?", "o": ["1910", "1911", "1912", "1913"], "c": 2 },
        { "q": "I. Dünya Savaşı'nı başlatan olay?", "o": ["Gemilerin batırılması", "Veliaht suikastı", "Sınır ihlali", "Ticari kriz"], "c": 1 },
        { "q": "Çanakkale'de 'Dur Yolcu' diyen şair?", "o": ["Necmettin Halil Onan", "Mehmet Akif", "Yahya Kemal", "Nazım Hikmet"], "c": 0 },
        { "q": "Mondros hangi gemide imzalandı?", "o": ["Hamidiye", "Agamemnon", "Goben", "Breslau"], "c": 1 },
        { "q": "Amasya Genelgesi'nin önemi?", "o": ["Savaş ilanı", "Milli mücadelenin planı", "Başkent seçimi", "Ordu kuruluşu"], "c": 1 },
        { "q": "Erzurum Kongresi başkanı?", "o": ["Kazım Karabekir", "Rauf Orbay", "Mustafa Kemal", "Ali Fuat Paşa"], "c": 2 },
        { "q": "Sivas Kongresi kararı?", "o": ["Manda kabulü", "Tam bağımsızlık", "Sadece Erzurum korunsun", "Padişaha bağlılık"], "c": 1 },
        { "q": "Sakarya Meydan Muharebesi süresi?", "o": ["10 gün", "22 gün 22 gece", "30 gün", "15 gün"], "c": 1 },
        { "q": "Saltanat ne zaman kaldırıldı?", "o": ["1 Kasım 1922", "29 Ekim 1923", "3 Mart 1924", "23 Nisan 1920"], "c": 0 },
        { "q": "Halifelik ne zaman kaldırıldı?", "o": ["1922", "1923", "1924", "1925"], "c": 2 },
        { "q": "Soyadı Kanunu yılı?", "o": ["1930", "1932", "1934", "1936"], "c": 2 },
        { "q": "Montrö'nün önemi?", "o": ["Boğazlar hakimiyeti", "Limanların açılması", "Sınırların çizilmesi", "Ekonomik yardım"], "c": 0 },
        { "q": "Hatay ana vatana ne zaman katıldı?", "o": ["1938", "1939", "1940", "1941"], "c": 1 },
        { "q": "II. Dünya Savaşı'na Türkiye ne zaman girdi?", "o": ["Başından beri", "Girdi ama savaşmadı (son an)", "Hiç girmedi", "1941"], "c": 1 },
        { "q": "Soğuk Savaş ne zaman başladı?", "o": ["1918", "1945", "1960", "1980"], "c": 1 },
        { "q": "Berlin Duvarı ne zaman yıkıldı?", "o": ["1985", "1989", "1991", "2000"], "c": 1 },
        { "q": "Sovyetler Birliği dağılma yılı?", "o": ["1989", "1990", "1991", "1995"], "c": 2 }
    ],
    "Coğrafya_P1": [
        { "q": "Türkiye'nin en uzun nehri?", "o": ["Fırat", "Dicle", "Kızılırmak", "Sakarya"], "c": 2 },
        { "q": "En büyük okyanus?", "o": ["Atlas", "Hint", "Pasifik", "Arktik"], "c": 2 },
        { "q": "Dünyanın en yüksek dağı?", "o": ["Everest", "K2", "Ağrı", "Alpler"], "c": 0 },
        { "q": "Türkiye'nin en büyük gölü?", "o": ["Tuz Gölü", "Van Gölü", "Beyşehir", "Eğirdir"], "c": 1 },
        { "q": "En çok yağış alan ilimiz?", "o": ["Trabzon", "Rize", "Artvin", "Giresun"], "c": 1 },
        { "q": "En büyük kıta?", "o": ["Afrika", "Amerika", "Asya", "Avrupa"], "c": 2 },
        { "q": "Brezilya'nın başkenti?", "o": ["Rio", "Sao Paulo", "Brasilia", "Salvador"], "c": 2 },
        { "q": "Japonya'nın başkenti?", "o": ["Osaka", "Kyoto", "Hiroşima", "Tokyo"], "c": 3 },
        { "q": "Süveyş Kanalı nereyi bağlar?", "o": ["Atlantik-Pasifik", "Akdeniz-Kızıldeniz", "Marmara-Ege", "Kuzey Denizi-Baltık"], "c": 1 },
        { "q": "Cebelitarık Boğazı kimler arasındadır?", "o": ["İspanya-Fas", "Yunanistan-Türkiye", "İtalya-Tunus", "Fransa-İngiltere"], "c": 0 },
        { "q": "Amazon ormanları hangi ülkededir?", "o": ["Peru", "Kolombiya", "Ekvador", "Brezilya"], "c": 3 },
        { "q": "En kalabalık ülke?", "o": ["Çin", "Hindistan", "ABD", "Rusya"], "c": 1 },
        { "q": "Yüzölçümü en büyük ülke?", "o": ["Rusya", "Kanada", "Çin", "ABD"], "c": 0 },
        { "q": "Türkiye'nin komşusu olmayan?", "o": ["Irak", "İran", "Mısır", "Suriye"], "c": 2 },
        { "q": "Ekvator'a en yakın ilimiz?", "o": ["Sinop", "Hatay", "Antalya", "Mersin"], "c": 1 },
        { "q": "Sinop'un özelliği?", "o": ["En güney", "En kuzey", "En doğu", "En batı"], "c": 1 },
        { "q": "Güneşin en son battığı ilimiz?", "o": ["Çanakkale", "Edirne", "İzmir", "Iğdır"], "c": 0 },
        { "q": "En geniş yüzölçümlü bölgemiz?", "o": ["Karadeniz", "Doğu Anadolu", "İç Anadolu", "Akdeniz"], "c": 1 },
        { "q": "Marmara'nın en yüksek dağı?", "o": ["Yıldız", "Uludağ", "Kartepe", "Samanlı"], "c": 1 },
        { "q": "Ege denizinin diğer adı?", "o": ["Adalar Denizi", "Mavi Deniz", "İç Deniz", "Beyaz Deniz"], "c": 0 },
        { "q": "En tuzlu denizimiz?", "o": ["Karadeniz", "Marmara", "Ege", "Akdeniz"], "c": 3 },
        { "q": "Nemrut Dağı (Heykeller olan) hangi ildedir?", "o": ["Adıyaman", "Bitlis", "Diyarbakır", "Urfa"], "c": 0 },
        { "q": "Peri bacaları hangi bölgededir?", "o": ["Ege", "İç Anadolu", "Akdeniz", "Karadeniz"], "c": 1 },
        { "q": "Pamukkale travertenleri nerededir?", "o": ["Aydın", "Denizli", "Muğla", "İzmir"], "c": 1 },
        { "q": "Dünyanın çatısı olarak bilinen yer?", "o": ["Andlar", "Alpler", "Tibet Platosu", "Kafkasya"], "c": 2 },
        { "q": "Nil Nehri hangi okyanusa/denize dökülür?", "o": ["Atlas", "Hint", "Akdeniz", "Kızıldeniz"], "c": 2 },
        { "q": "Mississippi Nehri hangi ülkededir?", "o": ["Kanada", "ABD", "Brezilya", "Arjantin"], "c": 1 },
        { "q": "En çok uyduya sahip gezegen?", "o": ["Jüpiter", "Satürn", "Mars", "Neptün"], "c": 1 },
        { "q": "Ay, Dünya'nın tek neyidir?", "o": ["Gezegeni", "Yıldızı", "Doğal uydusu", "Kozmik tozu"], "c": 2 },
        { "q": "Atmosferin en alt katmanı?", "o": ["Stratosfer", "Troposfer", "Mezosfer", "Termosfer"], "c": 1 },
        { "q": "Ozon tabakası hangi katmandadır?", "o": ["Troposfer", "Stratosfer", "Mezosfer", "Ekzosfer"], "c": 1 },
        { "q": "Fay hattı ne ile ilgilidir?", "o": ["Yağmur", "Rüzgar", "Deprem", "Sel"], "c": 2 },
        { "q": "TSunami'nin ana nedeni?", "o": ["Fırtına", "Deniz altı depremi", "Gelgit", "Küresel ısınma"], "c": 1 },
        { "q": "Erozyon'u önleyen en iyi yöntem?", "o": ["Betonlama", "Ağaçlandırma", "Sulama", "Gübreleme"], "c": 1 },
        { "q": "Maki hangi iklimin bitki örtüsü?", "o": ["Karasal", "Akdeniz", "Karadeniz", "Muson"], "c": 1 },
        { "q": "Bozkır (Stepe) nerede yaygın?", "o": ["Karadeniz", "Ege", "İç Anadolu", "Marmara"], "c": 2 },
        { "q": "Hangi kıtada hiç çöl yoktur?", "o": ["Avrupa", "Asya", "Afrika", "Avustralya"], "c": 0 },
        { "q": "Hangi kıtada hiç ülke yoktur?", "o": ["Okyanusya", "Antarktika", "Güney Amerika", "Asya"], "c": 1 },
        { "q": "Sahra çölü hangi kıtadır?", "o": ["Asya", "Afrika", "Avustralya", "Amerika"], "c": 1 },
        { "q": "Everest'in yüksekliği (m)?", "o": ["5137", "8125", "8848", "9250"], "c": 2 },
        { "q": "Dünya'nın merkezindeki sıcak katman?", "o": ["Manto", "Kabuk", "Çekirdek", "Magma"], "c": 2 },
        { "q": "Granit hangi tür kayaya örnektir?", "o": ["Püskürük", "Tortul", "Başkalaşım", "Yumuşak"], "c": 0 },
        { "q": "Hangi ülke adalar ülkesi değildir?", "o": ["Japonya", "Endonezya", "İngiltere", "İsviçre"], "c": 3 },
        { "q": "Avusturalya'nın diğer adı nedir?", "o": ["Kayıp Kıta", "Ada Kıta", "Yeşil Kıta", "Buz Kıta"], "c": 1 },
        { "q": "Hangi dil en çok kişi tarafından konuşulur?", "o": ["İngilizce", "İspanyolca", "Çince (Mandarin)", "Hintçe"], "c": 2 },
        { "q": "Dünyanın en küçük ülkesi?", "o": ["Monako", "Malta", "Vatikan", "Andorra"], "c": 2 },
        { "q": "Dünyanın en uzun tüneli nerededir?", "o": ["Japonya", "İsviçre", "Çin", "Norveç"], "c": 1 },
        { "q": "İzlanda'da çok olan şey nedir?", "o": ["Çöl", "Orman", "Gayzer ve Volkan", "Gökdelen"], "c": 2 },
        { "q": "Venedik'teki ulaşım aracı?", "o": ["Tren", "Metrobüs", "Gondol", "Fayton"], "c": 2 },
        { "q": "Grönland hangi ülkeye bağlıdır?", "o": ["Danimarka", "Norveç", "İsveç", "İzlanda"], "c": 0 }
    ],
    "Bilim_P1": [
        { "q": "Suyun kimyasal formülü?", "o": ["H2O", "CO2", "NaCl", "O2"], "c": 0 },
        { "q": "Hangi gezegen halkalıdır?", "o": ["Mars", "Venüs", "Satürn", "Neptün"], "c": 2 },
        { "q": "Yerçekimi kanununu kim buldu?", "o": ["Newton", "Einstein", "Tesla", "Edison"], "c": 0 },
        { "q": "Yüzey alanı en büyük organ?", "o": ["Karaciğer", "Deri", "Akciğer", "Bağırsak"], "c": 1 },
        { "q": "Işık hızı saniyede yaklaşık kaç km?", "o": ["100.000", "200.000", "300.000", "500.000"], "c": 2 },
        { "q": "Ampulü kim icat etti?", "o": ["Tesla", "Edison", "Bell", "Galileo"], "c": 1 },
        { "q": "Telefonu kim icat etti?", "o": ["Marconi", "Graham Bell", "Morse", "Newton"], "c": 1 },
        { "q": "Matematikte 'Pi' sayısı yaklaşık kaçtır?", "o": ["2.14", "3.14", "4.14", "5.14"], "c": 1 },
        { "q": "Bir üçgenin iç açıları toplamı?", "o": ["90", "180", "270", "360"], "c": 1 },
        { "q": "Evrim teorisi ile bilinen?", "o": ["Louis Pasteur", "Charles Darwin", "Gregor Mendel", "Stephen Hawking"], "c": 1 },
        { "q": "Modern fiziğin temellerinden 'E=mc2' kimin?", "o": ["Newton", "Einstein", "Bohr", "Planck"], "c": 1 },
        { "q": "Atomun çekirdeğinde ne bulunmaz?", "o": ["Proton", "Nötron", "Elektron", "Çekirdek"], "c": 2 },
        { "q": "DNA'nın yapısı?", "o": ["Tek sarmal", "Çift sarmal", "Düz", "Yıldız"], "c": 1 },
        { "q": "Kan gruplarında genel alıcı hangisidir?", "o": ["0", "A", "B", "AB"], "c": 3 },
        { "q": "Normal bir insanda kaç diş bulunur?", "o": ["28", "30", "32", "34"], "c": 2 },
        { "q": "Güneş'e en yakın gezegen?", "o": ["Venüs", "Merkür", "Dünya", "Mars"], "c": 1 },
        { "q": "Kızıl gezegen hangisidir?", "o": ["Venüs", "Mars", "Jüpiter", "Satürn"], "c": 1 },
        { "q": "Ay'a ilk ayak basan insan?", "o": ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Elon Musk"], "c": 1 },
        { "q": "İlk yapay uydu hangisidir?", "o": ["Apollo", "Sputnik", "Hubble", "Voyager"], "c": 1 },
        { "q": "Uzaya çıkan ilk insan?", "o": ["Yuri Gagarin", "John Glenn", "Neil Armstrong", "Shepard"], "c": 0 },
        { "q": "Fotosentez'de bitki ne üretir?", "o": ["Tuz", "Azot", "Şeker (Glikoz)", "Demir"], "c": 2 },
        { "q": "Hangi gaz olmazsa ateş yanmaz?", "o": ["Azot", "Oksijen", "Hidrojen", "Helyum"], "c": 1 },
        { "q": "En hafif element?", "o": ["Helyum", "Hidrojen", "Lityum", "Oksijen"], "c": 1 },
        { "q": "Demirin simgesi nedir?", "o": ["Fe", "I", "De", "Ir"], "c": 0 },
        { "q": "Altının simgesi nedir?", "o": ["Al", "Au", "Ag", "An"], "c": 1 },
        { "q": "Gümüşün simgesi nedir?", "o": ["Gi", "Ag", "Au", "G"], "c": 1 },
        { "q": "Cıva oda sıcaklığında ne haldedir?", "o": ["Katı", "Sıvı", "Gaz", "Plazma"], "c": 1 },
        { "q": "Bir bilgisayarın 'beyni' sayılan parça?", "o": ["RAM", "HDD", "CPU (İşlemci)", "GPU"], "c": 2 },
        { "q": "İnternet'in öncüsü sayılan ağ?", "o": ["Netscape", "ARPANET", "Yahoo", "Google"], "c": 1 },
        { "q": "Kuduz aşısını kim buldu?", "o": ["Louis Pasteur", "Alexander Fleming", "Robert Koch", "Marie Curie"], "c": 0 },
        { "q": "Penisilini (ilk antibiyotik) kim buldu?", "o": ["Pasteur", "Fleming", "Newton", "Bohr"], "c": 1 },
        { "q": "X ışınlarını kim keşfetti?", "o": ["Roentgen", "Curie", "Tesla", "Planck"], "c": 0 },
        { "q": "Marie Curie hangi dalda Nobel aldı?", "o": ["Fizik", "Kimya", "Fizik ve Kimya", "Yalnızca Tıp"], "c": 2 },
        { "q": "Yarasalar yönlerini nasıl bulur?", "o": ["Gözleriyle", "Ses dalgalarıyla (Ekolokasyon)", "Koklayarak", "Magnetizm ile"], "c": 1 },
        { "q": "Hangi hayvan uçabilen tek memelidir?", "o": ["Penguen", "Yarasa", "Devekuşu", "Kartal"], "c": 1 },
        { "q": "Dünyanın en hızlı kara hayvanı?", "o": ["Aslan", "Çita", "At", "Kaplan"], "c": 1 },
        { "q": "Balinalar balık mıdır?", "o": ["Evet", "Hayır (Memelidir)", "Kusursuz balıktır", "Yarı balıktır"], "c": 1 },
        { "q": "Arılar ne toplayarak bal yapar?", "o": ["Su", "Polen ve Nektar", "Toprak", "Yaprak"], "c": 1 },
        { "q": "Depremin büyüklüğünü ölçen alet?", "o": ["Termometre", "Barometre", "Sismograf", "Kronometre"], "c": 2 },
        { "q": "Sıcaklığı ne ölçer?", "o": ["Barometre", "Termometre", "Higrometre", "Anemometre"], "c": 1 },
        { "q": "Hava basıncını ne ölçer?", "o": ["Barometre", "Termometre", "Pusula", "Altimetre"], "c": 0 },
        { "q": "Radyoaktiflik birimlerinden biri nedir?", "o": ["Watt", "Joule", "Becquerel", "Volt"], "c": 2 },
        { "q": "Elektrik akım birimi nedir?", "o": ["Volt", "Amper", "Ohm", "Watt"], "c": 1 },
        { "q": "Bir pilin üzerinde 'V' neyi temsil eder?", "o": ["Volkan", "Volt (Gerilim)", "Vites", "Vakum"], "c": 1 },
        { "q": "Yer çekimi dünyada her yerde aynı mıdır?", "o": ["Evet", "Hayır (Kutuplarda daha fazla)", "Ekvatorda daha fazla", "Sadece denizde var"], "c": 1 },
        { "q": "Gökkuşağında kaç renk vardır?", "o": ["5", "6", "7", "8"], "c": 2 },
        { "q": "Hangi renk ışık en çok kırılır?", "o": ["Kırmızı", "Mavi", "Yeşil", "Mor"], "c": 3 },
        { "q": "Ses vakumda (boşlukta) yayılır mı?", "o": ["Evet", "Hayır", "Sadece yüksek sesle", "Sadece ışıkla"], "c": 1 },
        { "q": "Mıknatıs hangi metali çekmez?", "o": ["Demir", "Çelik", "Altın", "Nikel"], "c": 2 },
        { "q": "Elmas neyin kristalleşmiş halidir?", "o": ["Kömür (Karbon)", "Demir", "Kuvars", "Cam"], "c": 0 }
    ],
    "Kültür_P1": [
        { "q": "Mona Lisa tablosu kime aittir?", "o": ["Picasso", "Van Gogh", "Leonardo da Vinci", "Dalí"], "c": 2 },
        { "q": "İstiklal Marşı'nın yazarı?", "o": ["Yahya Kemal", "Necip Fazıl", "Mehmet Akif Ersoy", "Namık Kemal"], "c": 2 },
        { "q": "Nobel alan ilk Türk yazar?", "o": ["Yaşar Kemal", "Zülfü Livaneli", "Orhan Pamuk", "Aziz Nesin"], "c": 2 },
        { "q": "Piyanoda kaç tuş vardır?", "o": ["64", "76", "88", "102"], "c": 2 },
        { "q": "Eyfel Kulesi hangi şehirdedir?", "o": ["Berlin", "Londra", "Roma", "Paris"], "c": 3 },
        { "q": "Hangi ressam kulağını kesmiştir?", "o": ["Picasso", "Van Gogh", "Monet", "Dalí"], "c": 1 },
        { "q": "Don Kişot'un yazarı?", "o": ["Dante", "Cervantes", "Shakespeare", "Goethe"], "c": 1 },
        { "q": "Hamlet'in yazarı?", "o": ["Tolstoy", "Dostoyevski", "Shakespeare", "Moliere"], "c": 2 },
        { "q": "Suç ve Ceza'nın yazarı?", "o": ["Puşkin", "Gogol", "Dostoyevski", "Tolstoy"], "c": 2 },
        { "q": "İlahi Komedya'nın yazarı?", "o": ["Boccaccio", "Petrarca", "Dante", "Machiavelli"], "c": 2 },
        { "q": "Türkçenin ilk sözlüğü?", "o": ["Kutadgu Bilig", "Divan-ı Lügatit Türk", "Atabetül Hakayık", "Muhakemetül Lügateyn"], "c": 1 },
        { "q": "İlk Türk romanı?", "o": ["Araba Sevdası", "Mai ve Siyah", "Taaşşuk-ı Talat ve Fitnat", "İntibah"], "c": 2 },
        { "q": "Sefiller'in yazarı?", "o": ["Zola", "Balzac", "Victor Hugo", "Flaubert"], "c": 2 },
        { "q": "Satrançta en güçlü taş?", "o": ["Şah", "Vezir", "Kale", "Fil"], "c": 1 },
        { "q": "Olimpiyat halkaları kaç adettir?", "o": ["4", "5", "6", "7"], "c": 1 },
        { "q": "Hangi nota 'Porte'nin en alt çizgisindedir?", "o": ["Do", "Re", "Mi", "Fa"], "c": 2 },
        { "q": "İtalyan mutfağının ünlü çorbası?", "o": ["Gazpacho", "Minestrone", "Bouillabaisse", "Borscht"], "c": 1 },
        { "q": "Sushi hangi ülkeye aittir?", "o": ["Çin", "Kore", "Tayland", "Japonya"], "c": 3 },
        { "q": "Pizza'nın vatanı?", "o": ["Fransa", "İtalya", "İspanya", "Yunanistan"], "c": 1 },
        { "q": "Döner hangi mutfağa aittir?", "o": ["Yunan", "Arap", "Türk", "İran"], "c": 2 },
        { "q": "Grammy ödülleri hangi alanda verilir?", "o": ["Sinema", "Müzik", "Edebiyat", "Tiyatro"], "c": 1 },
        { "q": "Altın Palmiye hangi festivaldedir?", "o": ["Venedik", "Berlin", "Cannes", "Antalya"], "c": 2 },
        { "q": "Oscar heykelciğinin resmi adı?", "o": ["Kupa", "Akademi Ödülü", "Altın Adam", "Yüzük"], "c": 1 },
        { "q": "Heykeltıraş Rodin'in en ünlü eseri?", "o": ["Düşünen Adam", "Davut", "Pietà", "Özgürlük Anıtı"], "c": 0 },
        { "q": "Beethoven kaçıncı senfonisini sağır yazdı?", "o": ["3", "5", "7", "9"], "c": 3 },
        { "q": "Mozart'ın 'Saraydan Kız Kaçırma' operası nerede geçer?", "o": ["Viyana", "İstanbul", "Roma", "Paris"], "c": 1 },
        { "q": "Semazenlerin giydiği şapka?", "o": ["Fes", "Sikke", "Sarık", "Kalpak"], "c": 1 },
        { "q": "Mesnevi'nin yazarı?", "o": ["Yunus Emre", "Mevlana", "Hacı Bektaş", "Fuzuli"], "c": 1 },
        { "q": "Matbaa Türkiye'ye ne zaman geldi (Lale Devri)?", "o": ["1720", "1727", "1730", "1740"], "c": 1 },
        { "q": "İlk Türk matbaacısı?", "o": ["İbrahim Müteferrika", "Evliya Çelebi", "Katip Çelebi", "Nafi"], "c": 0 },
        { "q": "Gırgır dergisinin kurucusu?", "o": ["Oğuz Aral", "Tekin Aral", "Galip Tekin", "Ergün Gündüz"], "c": 0 },
        { "q": "Hacivat ve Karagöz hangi sanat türüdür?", "o": ["Meddah", "Gölge Oyunu", "Orta Oyunu", "Kukla"], "c": 1 },
        { "q": "Midas'ın kulakları kime aittir?", "o": ["Yunan Mitolojisi", "Frigya", "Lidya", "Hitit"], "c": 1 },
        { "q": "Truva atı hangi şehir için yapıldı?", "o": ["Çanakkale", "İzmir", "Atina", "Sparta"], "c": 0 },
        { "q": "Zeus hangi dağda yaşar?", "o": ["Ağrı", "Everest", "Olimpos", "İda"], "c": 2 },
        { "q": "Aşil'in zayıf noktası?", "o": ["Gözü", "Topuğu", "Omzu", "Eli"], "c": 1 },
        { "q": "Mısırlıların kutsal saydığı hayvan?", "o": ["İnek", "Kedi", "Köpek", "At"], "c": 1 },
        { "q": "Sfinks'in vücudu hangi hayvandır?", "o": ["Aslan", "At", "Boğa", "Kartal"], "c": 0 },
        { "q": "Vikingler nerelidir?", "o": ["İngiltere", "İskandinavya", "Almanya", "İzlanda"], "c": 1 },
        { "q": "Bumerang hangi yerlilere aittir?", "o": ["Aztek", "İnka", "Aborjin", "Maori"], "c": 2 },
        { "q": "Flamenko hangi ülkenin dansıdır?", "o": ["Portekiz", "İspanya", "Arjantin", "Meksika"], "c": 1 },
        { "q": "Tango nerede doğmuştur?", "o": ["İspanya", "Brezilya", "Arjantin", "Küba"], "c": 2 },
        { "q": "Samba nerenin dansıdır?", "o": ["Meksika", "İspanya", "Brezilya", "Portekiz"], "c": 2 },
        { "q": "Bale nerede başlamıştır?", "o": ["Rusya", "Fransa", "İtalya", "Almanya"], "c": 2 },
        { "q": "Çay nerenin milli içeceğidir?", "o": ["İngiltere", "Çin", "Türkiye", "Hindistan"], "c": 2 },
        { "q": "Kahve'nin ana vatanı?", "o": ["Brezilya", "Kolombiya", "Etiyopya", "Yemen"], "c": 2 },
        { "q": "Çikolata neyden yapılır?", "o": ["Vanilya", "Kakao", "Fındık", "Süt"], "c": 1 },
        { "q": "Baget ekmeği nerenindir?", "o": ["Almanya", "Fransa", "İtalya", "Belçika"], "c": 1 },
        { "q": "Kruvasan nerenindir?", "o": ["Fransa", "Avusturya", "Almanya", "İsviçre"], "c": 1 },
        { "q": "Hamburger adı hangi şehirden gelir?", "o": ["Berlin", "Hamburg", "New York", "Münih"], "c": 1 }
    ],
    "Spor_P1": [
        { "q": "Dünya Kupası'nı en çok kazanan?", "o": ["Almanya", "İtalya", "Brezilya", "Arjantin"], "c": 2 },
        { "q": "Euro 2008 şampiyonu?", "o": ["Türkiye", "Almanya", "İspanya", "Rusya"], "c": 2 },
        { "q": "Basketbolda bir maç kaç periyottur?", "o": ["2", "3", "4", "5"], "c": 2 },
        { "q": "NBA'in logosundaki oyuncu?", "o": ["Michael Jordan", "Jerry West", "Magic Johnson", "Larry Bird"], "c": 1 },
        { "q": "Wimbledon hangi sporun turnuvasıdır?", "o": ["Golf", "Tenis", "Kriket", "Polo"], "c": 1 },
        { "q": "Tenis maçında 'Love' ne demektir?", "o": ["Aşk", "Sıfır", "Beraberlik", "Oyun sonu"], "c": 1 },
        { "q": "Voleybolda bir takım sahada kaç kişidir?", "o": ["5", "6", "7", "8"], "c": 1 },
        { "q": "Hentbolda oyuncu sayısı?", "o": ["6", "7", "11", "12"], "c": 1 },
        { "q": "Su polosu kalede kaç kişiyle oynanır?", "o": ["1", "2", "3", "0"], "c": 0 },
        { "q": "Buz hokeyi diskinin adı?", "o": ["Ball", "Puck", "Disk", "Ring"], "c": 1 },
        { "q": "Curling hangi zeminde oynanır?", "o": ["Çim", "Toprak", "Buz", "Asfalt"], "c": 2 },
        { "q": "Formula 1'in efsanesi (Alman)?", "o": ["Senna", "Hamilton", "Schumacher", "Vettel"], "c": 2 },
        { "q": "MotoGP'nin efsanesi (İtalyan)?", "o": ["Rossi", "Marquez", "Lorenzo", "Dovizioso"], "c": 0 },
        { "q": "Usain Bolt hangi ülkelidir?", "o": ["ABD", "Nijerya", "Jamaika", "Küba"], "c": 2 },
        { "q": "Maraton kaç kilometredir (yaklaşık)?", "o": ["21", "30", "42", "50"], "c": 2 },
        { "q": "Olimpiyatlar kaç yılda bir yapılır?", "o": ["2", "3", "4", "5"], "c": 2 },
        { "q": "İlk modern olimpiyatlar nerede yapıldı?", "o": ["Londra", "Paris", "Atina", "Roma"], "c": 2 },
        { "q": "Türkiye'nin ilk olimpiyat altını?", "o": ["Naim Süleymanoğlu", "Yaşar Erkan", "Hamza Yerlikaya", "Mete Gazoz"], "c": 1 },
        { "q": "Cep Herkülü lakaplı halterci?", "o": ["Halil Mutlu", "Naim Süleymanoğlu", "Taner Sağır", "Nurcan Taylan"], "c": 1 },
        { "q": "Mete Gazoz hangi branşta altın aldı?", "o": ["Güreş", "Halter", "Okçuluk", "Boks"], "c": 2 },
        { "q": "Filenin Sultanları hangi sporu yapar?", "o": ["Basketbol", "Voleybol", "Hentbol", "Tenis"], "c": 1 },
        { "q": "Kırkpınar güreşleri nerede yapılır?", "o": ["Çanakkale", "Edirne", "Bursa", "Tekirdağ"], "c": 1 },
        { "q": "Satranç bir spor mudur?", "o": ["Hayır", "Sadece oyundur", "Evet (Zihin sporu)", "Tartışmalıdır"], "c": 2 },
        { "q": "Bilardo'da kaç top var (Amerikan)?", "o": ["9", "15", "16", "22"], "c": 2 },
        { "q": "Bowling'de devrilen şeylere ne denir?", "o": ["Pin", "Taş", "Kuka", "Top"], "c": 0 },
        { "q": "Golf'te topu deliğe sokmaya ne denir?", "o": ["Gol", "Putt", "Birdie", "Eagle"], "c": 1 },
        { "q": "Korumalı futbol nerede popülerdir?", "o": ["İngiltere", "Brezilya", "ABD", "Almanya"], "c": 2 },
        { "q": "Beyzbol kaç vuruş hakkı verir?", "o": ["1", "2", "3", "4"], "c": 2 },
        { "q": "Tour de France hangi spor dalıdır?", "o": ["Koşu", "Yüzme", "Bisiklet", "Yelken"], "c": 2 },
        { "q": "Yüzmede 'Kelebek' bir stili midir?", "o": ["Evet", "Hayır", "Sadece antrenmandır", "Kuvbağalamadır"], "c": 0 },
        { "q": "Michael Phelps kaç altın aldı (toplam)?", "o": ["13", "18", "23", "28"], "c": 2 },
        { "q": "Roger Federer hangi branşta efsanedir?", "o": ["Futbol", "Basketbol", "Tenis", "Golf"], "c": 2 },
        { "q": "Tiger Woods hangi sporu yapar?", "o": ["Tenis", "Golf", "Bilardo", "Polo"], "c": 1 },
        { "q": "Sumo güreşi hangi ülkenindir?", "o": ["Çin", "Japonya", "Kore", "Moğolistan"], "c": 1 },
        { "q": "Judo'nun anlamı nedir?", "o": ["Sert yol", "Nazik yol", "Doğru yol", "Kısa yol"], "c": 1 },
        { "q": "Karate nerede doğmuştur?", "o": ["Çin", "Okinawa (Japonya)", "Tayland", "Vietnam"], "c": 1 },
        { "q": "Taekwondo nerenindir?", "o": ["Japonya", "Kore", "Çin", "Tayvan"], "c": 1 },
        { "q": "Muay Thai nerenindir?", "o": ["Çin", "Vietnam", "Tayland", "Kamboçya"], "c": 2 },
        { "q": "Boks maçı kaç raunttur (pro)?", "o": ["10", "12", "15", "20"], "c": 1 },
        { "q": "Muhammed Ali'nin asıl adı?", "o": ["Cassius Clay", "Joe Louis", "Mike Tyson", "George Foreman"], "c": 0 },
        { "q": "Efsane basketbolcu 'Kobe Bryant'ın lakabı?", "o": ["The Answer", "Black Mamba", "The King", "Air"], "c": 1 },
        { "q": "LeBron James hangi sporu yapar?", "o": ["Futbol", "Basketbol", "NFL", "MLB"], "c": 1 },
        { "q": "Lionel Messi nerelidir?", "o": ["İspanya", "Brezilya", "Arjantin", "Uruguay"], "c": 2 },
        { "q": "Cristiano Ronaldo nerelidir?", "o": ["Brezilya", "İspanya", "Portekiz", "İtalya"], "c": 2 },
        { "q": "Zinedine Zidane hangi milli takımdadır?", "o": ["Cezayir", "Fransa", "Fas", "Tunus"], "c": 1 },
        { "q": "Türkiye'nin UEFA kupası kazanan takımı?", "o": ["Fenerbahçe", "Beşiktaş", "Galatasaray", "Trabzonspor"], "c": 2 },
        { "q": "Şampiyonlar Ligi kupasının lakabı?", "o": ["Altın Kupa", "Dev Kulak", "Gümüş Tepsi", "Büyük Kanat"], "c": 1 },
        { "q": "Futbolda ofsayt kuralı ne zaman geldi (yüzyıl)?", "o": ["18", "19", "20", "21"], "c": 1 },
        { "q": "İlk Dünya Kupası nerede yapıldı?", "o": ["Brezilya", "Uruguay", "Fransa", "İtalya"], "c": 1 },
        { "q": "En çok şampiyonluk yaşayan NBA takımı?", "o": ["Lakers", "Celtics", "Bulls", "Warriors"], "c": 1 }
    ],
    "Sanat_P1": [
        { "q": "Davut heykeli kimin?", "o": ["Leonardo", "Michelangelo", "Donatello", "Raphael"], "c": 1 },
        { "q": "Pietà heykeli kimin?", "o": ["Bernini", "Michelangelo", "Rodin", "Canova"], "c": 1 },
        { "q": "Guernica tablosu kimin?", "o": ["Picasso", "Dalí", "Miró", "Goya"], "c": 0 },
        { "q": "Belleğin Azmi (Eriyen Saatler)?", "o": ["Magritte", "Dalí", "Picasso", "Warhol"], "c": 1 },
        { "q": "İnci Küpeli Kız kimin?", "o": ["Rembrandt", "Vermeer", "Hals", "Steen"], "c": 1 },
        { "q": "Gece Devriyesi kimin?", "o": ["Vermeer", "Rembrandt", "Rubens", "Van Dyck"], "c": 1 },
        { "q": "Yıldızlı Gece kimin?", "o": ["Van Gogh", "Gauguin", "Cézanne", "Monet"], "c": 0 },
        { "q": "Çığlık tablosu kimin?", "o": ["Munch", "Klimt", "Kokoschka", "Schiele"], "c": 0 },
        { "q": "Öpücük tablosu kimin?", "o": ["Munch", "Klimt", "Monet", "Degas"], "c": 1 },
        { "q": "Son Akşam Yemeği freski?", "o": ["Michelangelo", "Leonardo", "Raphael", "Botticelli"], "c": 1 },
        { "q": "Venüs'ün Doğuşu kimin?", "o": ["Botticelli", "Tiziano", "Veronese", "Tintoretto"], "c": 0 },
        { "q": "Atina Okulu freski?", "o": ["Michelangelo", "Raphael", "Leonardo", "Bramante"], "c": 1 },
        { "q": "Sistine Şapeli tavanı?", "o": ["Leonardo", "Michelangelo", "Raphael", "Perugino"], "c": 1 },
        { "q": "Kaplumbağa Terbiyecisi?", "o": ["Şeker Ahmet Paşa", "Osman Hamdi Bey", "Hoca Ali Rıza", "İbrahim Çallı"], "c": 1 },
        { "q": "Mihrap tablosu kimin?", "o": ["Osman Hamdi Bey", "Şevket Dağ", "Halil Paşa", "Avni Arbaş"], "c": 0 },
        { "q": "Kübizm akımının öncüsü?", "o": ["Monet", "Picasso", "Dalí", "Kandinsky"], "c": 1 },
        { "q": "Sürrealizm akımının öncüsü?", "o": ["Picasso", "Dalí", "Matisse", "Renoir"], "c": 1 },
        { "q": "Empresyonizm (İzlenimcilik) öncüsü?", "o": ["Monet", "Manet", "Degas", "Renoir"], "c": 0 },
        { "q": "Pop Art akımının öncüsü?", "o": ["Warhol", "Lichtenstein", "Hockney", "Hamilton"], "c": 0 },
        { "q": "Soyut sanatın öncüsü?", "o": ["Picasso", "Kandinsky", "Mondrian", "Malevich"], "c": 1 },
        { "q": "Dünyanın en büyük müzesi?", "o": ["Louvre", "British Museum", "Metropolitan", "Hermitage"], "c": 0 },
        { "q": "Louvre Müzesi nerededir?", "o": ["Londra", "Paris", "Berlin", "Madrid"], "c": 1 },
        { "q": "Hermitage Müzesi nerededir?", "o": ["Moskova", "St. Petersburg", "Kiev", "Varşova"], "c": 1 },
        { "q": "Uffizi Galerisi nerededir?", "o": ["Roma", "Venedik", "Floransa", "Milano"], "c": 2 },
        { "q": "Prado Müzesi nerededir?", "o": ["Barcelona", "Madrid", "Lizbon", "Sevilla"], "c": 1 },
        { "q": "Guggenheim Müzesi (modern mimari)?", "o": ["Paris", "Bilbao", "Roma", "Viyana"], "c": 1 },
        { "q": "Ayasofya hangi şehirdedir?", "o": ["İstanbul", "Atina", "Roma", "Kahire"], "c": 0 },
        { "q": "Sagrada Familia (bitmeyen kilise)?", "o": ["Madrid", "Barcelona", "Sevilla", "Valencia"], "c": 1 },
        { "q": "Tac Mahal hangi ülkededir?", "o": ["Pakistan", "Hindistan", "İran", "Afganistan"], "c": 1 },
        { "q": "Kolezyum nerededir?", "o": ["Atina", "Roma", "Paris", "Londra"], "c": 1 },
        { "q": "Pisa Kulesi neden eğiktir?", "o": ["Deprem", "Zemin çökmesi", "Hatalı tasarım", "Savaş"], "c": 1 },
        { "q": "Özgürlük Anıtı hangi ülkeden hediye?", "o": ["İngiltere", "Fransa", "Almanya", "İtalya"], "c": 1 },
        { "q": "Venedik neyi ile ünlüdür?", "o": ["Kanalları", "Dağları", "Ormanları", "Çölleri"], "c": 0 },
        { "q": "Barok sanatının efsanesi?", "o": ["Bernini", "Michelangelo", "Donatello", "Rodin"], "c": 0 },
        { "q": "Gotik mimarinin en belirgin özelliği?", "o": ["Kalın duvarlar", "Sivri kemerler", "Küçük pencereler", "Düz çatılar"], "c": 1 },
        { "q": "Bauhaus okulu hangi ülkededir?", "o": ["Fransa", "Almanya", "Avusturya", "İsviçre"], "c": 1 },
        { "q": "Art Nouveau ne demektir?", "o": ["Eski Sanat", "Yeni Sanat", "Güzel Sanat", "Büyük Sanat"], "c": 1 },
        { "q": "Frida Kahlo hangi ülkelidir?", "o": ["İspanya", "Brezilya", "Meksika", "Şili"], "c": 2 },
        { "q": "Diego Rivera kimin eşidir?", "o": ["Frida Kahlo", "Georgia O'Keeffe", "Cindy Sherman", "Yoko Ono"], "c": 0 },
        { "q": "Banksy ne tür bir sanatçıdır?", "o": ["Ressam", "Heykeltıraş", "Sokak Sanatçısı", "Fotoğrafçı"], "c": 2 },
        { "q": "Ebru sanatı neyde yapılır?", "o": ["Kağıt", "Su", "Tuval", "Duvar"], "c": 1 },
        { "q": "Hat sanatı nedir?", "o": ["Resim", "Güzel yazı", "Dokuma", "Çini"], "c": 1 },
        { "q": "Mistik dansın (Sema) kostümü?", "o": ["Cübbe", "Tennoure", "Kaftan", "Entari"], "c": 1 },
        { "q": "Ney hangi bitkiden yapılır?", "o": ["Ağaç", "Kamış", "Bambu", "Plastik"], "c": 1 },
        { "q": "Opera'nın vatanı neresidir?", "o": ["Almanya", "İtalya", "Fransa", "Avusturya"], "c": 1 },
        { "q": "Senfoni Orkestrası şefi ne kullanır?", "o": ["Asa", "Baton", "Çubuk", "Mızrap"], "c": 1 },
        { "q": "Kemanın bir tık büyüğü?", "o": ["Viyola", "Çello", "Kontrbas", "Gitar"], "c": 0 },
        { "q": "Hangi çalgı telli değildir?", "o": ["Arp", "Kanun", "Kaval", "Ud"], "c": 2 },
        { "q": "Sinemanın mucitleri sayılan kardeşler?", "o": ["Wright", "Lumière", "Grimm", "Coen"], "c": 1 },
        { "q": "İlk sesli film?", "o": ["Caz Şarkıcısı", "Modern Zamanlar", "Yurttaş Kane", "Metropolis"], "c": 0 }
    ]
};
